#!/usr/bin/env bash
# =============================================================================
# OpenCode Dev Container Feature — install.sh
# https://github.com/danismeup/devcontainer-feature-opencode
# =============================================================================
set -euo pipefail

VERSION="${VERSION:-latest}"
WEB_PORT="${WEBPORT:-4096}"
START_WEB="${STARTWEBOONCREATE:-false}"
DATA_DIR_RELATIVE="${DATADIRRELATIVE:-.opencode/data}"

echo "[opencode-feature] Installing OpenCode (version: ${VERSION})..."

# ---------------------------------------------------------------------------
# 1. Install OpenCode
# ---------------------------------------------------------------------------
if command -v opencode &>/dev/null && [ "${VERSION}" = "latest" ]; then
  echo "[opencode-feature] OpenCode already installed ($(opencode --version 2>/dev/null || echo 'unknown version')). Skipping."
else
  if [ "${VERSION}" = "latest" ]; then
    curl -fsSL https://opencode.ai/install | bash
  else
    curl -fsSL "https://opencode.ai/install" | bash -s -- --version "${VERSION}"
  fi
fi

echo "[opencode-feature] OpenCode installed: $(opencode --version 2>/dev/null || echo 'ok')"

# ---------------------------------------------------------------------------
# 2. Write project-level opencode.jsonc (only if not already present)
# ---------------------------------------------------------------------------
OPENCODE_CONFIG="${_REMOTE_USER_HOME:-/root}/.config/opencode/config.json"
mkdir -p "$(dirname "${OPENCODE_CONFIG}")"

if [ ! -f "${OPENCODE_CONFIG}" ]; then
  cat > "${OPENCODE_CONFIG}" <<EOF
{
  // OpenCode global config — generated by devcontainer-feature-opencode
  // Override per-project via opencode.jsonc in the repo root
  "autoshare": false
}
EOF
  echo "[opencode-feature] Default global config written to ${OPENCODE_CONFIG}"
fi

# ---------------------------------------------------------------------------
# 3. Write helper script: opencode-web-start.sh
# ---------------------------------------------------------------------------
cat > /usr/local/bin/opencode-web-start <<'SCRIPT'
#!/usr/bin/env bash
# Start OpenCode web UI — called automatically by postStartCommand or manually
set -euo pipefail
PORT="${OPENCODE_WEB_PORT:-4096}"
echo "[opencode] Starting web UI on port ${PORT}..."
exec opencode web --hostname 0.0.0.0 --port "${PORT}"
SCRIPT
chmod +x /usr/local/bin/opencode-web-start
echo "[opencode-feature] Helper script written to /usr/local/bin/opencode-web-start"

# ---------------------------------------------------------------------------
# 4. Write .gitignore snippet for OPENCODE_DATA_DIR
# ---------------------------------------------------------------------------
GITIGNORE_SNIPPET_DIR="/usr/local/share/opencode-feature"
mkdir -p "${GITIGNORE_SNIPPET_DIR}"
cat > "${GITIGNORE_SNIPPET_DIR}/gitignore-snippet.txt" <<'EOF'
# OpenCode — session data, snapshots, logs (managed by devcontainer-feature-opencode)
.opencode/data/
.opencode/auth.json
EOF
echo "[opencode-feature] .gitignore snippet saved to ${GITIGNORE_SNIPPET_DIR}/gitignore-snippet.txt"

# ---------------------------------------------------------------------------
# 5. Optionally schedule web start via postStartCommand marker
# ---------------------------------------------------------------------------
if [ "${START_WEB}" = "true" ]; then
  echo "[opencode-feature] startWebOnCreate=true — marking for postStartCommand"
  # We write a marker; the devcontainer.json should include:
  # "postStartCommand": "opencode-web-start &"
  mkdir -p /usr/local/share/opencode-feature
  echo "true" > /usr/local/share/opencode-feature/start-web-on-create
fi

echo "[opencode-feature] Done."
